<?php
$cms_validations = [
    'email' =>
      ['label' => 'Email',
       'component' => 'PTValidator',
       'method' => 'cms_is_valid_email',
       'order' => 100,
       'type' => 'text'],
    'url' =>
      ['label' => 'URL',
       'component' => 'PTValidator',
       'method' => 'cms_is_valid_url',
       'order' => 200,
       'type' => 'text'],
    'tel' =>
      ['label' => 'Tel',
       'component' => 'PTValidator',
       'method' => 'cms_is_valid_tel',
       'order' => 400,
       'type' => 'text'],
    'postal_code' =>
      ['label' => 'Postal Code',
       'component' => 'PTValidator',
       'method' => 'cms_is_valid_postal_code',
       'order' => 500,
       'type' => 'text'],
    'hiragana' =>
      ['label' => 'Hiragana',
       'component' => 'PTValidator',
       'method' => 'cms_is_valid_hiragana',
       'order' => 600,
       'type' => 'text'],
    'katakana' =>
      ['label' => 'Katakana',
       'component' => 'PTValidator',
       'method' => 'cms_is_valid_katakana',
       'order' => 700,
       'type' => 'text'],
    'number' =>
      ['label' => 'Number',
       'component' => 'PTValidator',
       'method' => 'cms_is_valid_number',
       'order' => 800,
       'type' => 'text'],
    'alphanumeric_symbols' =>
      ['label' => 'Alphanumeric Symbols',
       'component' => 'PTValidator',
       'method' => 'cms_is_alphanumeric_symbols',
       'order' => 900,
       'type' => 'text'],
    'required' =>
      ['label' => 'Required',
       'component' => 'PTValidator',
       'method' => 'cms_required',
       'order' => 1000,
       'force' => true,
       'type' => 'boolean'],
];
$this->registry['cms_validations'] = $cms_validations;